spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(65u6Bwx0lQY/Qd+4RHIgHCqKCuWvg/WDJ0/bEw58P/CFeSVuqIKsLi8daYUoe39CcRnOS34H3+mpaEnMBFqOHodPCDnyuVMt/leRIbO58lyKv2MErPeWC+n5jXZsRZ0809TFDK6sujWQghi1Rxjit9trbzylFJ7Bzo3JRFwsEHU=)
    #url: jdbc:mysql://112.228.211.194:3306/mh?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    #url: jdbc:mysql://localhost:3307/mh?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    #username: ENC(kJKZxiBvZ/36/js2QphSMA==)
    username: ENC(mZM85xKW7UKEuQAL7Riv5w==)
    password: ENC(S3GZTYnC45YzLE0HpI0MzA==)
    #password: ENC(UrnzNMv0uxnux53u7WKiHQ==)

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

jasypt:
  encryptor:
    password: ${PASSWORD}
